import PDFDocument from "pdfkit";
import XLSX from "xlsx";

function sanitizeExcelValue(value) {
  if (typeof value !== "string") return value;
  if (/^[=+\-@]/.test(value)) {
    return `'${value}`;
  }
  return value;
}

function stringifyValue(value) {
  if (value === null || value === undefined) return "";
  if (Array.isArray(value)) return value.join(", ");
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

export const exportService = {
  async buildPdf({ title, generatedBy, filters, columns, rows }) {
    const doc = new PDFDocument({ margin: 40, size: "A4", layout: columns.length > 6 ? "landscape" : "portrait" });
    const chunks = [];

    return new Promise((resolve, reject) => {
      doc.on("data", (chunk) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      doc.fontSize(18).text("Rural Health Management System", { align: "center" });
      doc.moveDown(0.3);
      doc.fontSize(14).text(title, { align: "center" });
      doc.moveDown(0.6);
      doc.fontSize(9).text(`Generated by: ${generatedBy}`);
      doc.text(`Generated at: ${new Date().toLocaleString("en-IN")}`);
      doc.text(`Applied filters: ${JSON.stringify(filters)}`);
      doc.moveDown();

      doc.fontSize(10);
      columns.forEach((column, index) => {
        doc.text(column, 40 + index * 90, doc.y, { width: 85, continued: index < columns.length - 1 });
      });
      doc.moveDown(0.5);

      rows.slice(0, 100).forEach((row) => {
        columns.forEach((column, index) => {
          doc.text(stringifyValue(row[column]), 40 + index * 90, doc.y, { width: 85, continued: index < columns.length - 1 });
        });
        doc.moveDown(0.4);
      });

      doc.moveDown();
      doc.fontSize(8).text("Confidential - role restricted operational report", { align: "right" });
      doc.end();
    });
  },

  async buildXlsx({ sheetName, columns, rows, filters, title }) {
    const worksheetRows = rows.map((row) =>
      Object.fromEntries(columns.map((column) => [column, sanitizeExcelValue(stringifyValue(row[column]))])),
    );
    const worksheet = XLSX.utils.json_to_sheet(worksheetRows);
    const summarySheet = XLSX.utils.json_to_sheet([
      { title, generatedAt: new Date().toISOString(), filters: JSON.stringify(filters) },
    ]);
    const workbook = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(workbook, summarySheet, "Summary");
    XLSX.utils.book_append_sheet(workbook, worksheet, sheetName);
    return XLSX.write(workbook, { type: "buffer", bookType: "xlsx" });
  },

  async buildCsv({ columns, rows }) {
    const header = columns.join(",");
    const dataRows = rows.map((row) =>
      columns
        .map((column) => {
          const safe = sanitizeExcelValue(stringifyValue(row[column]));
          return `"${String(safe).replaceAll('"', '""')}"`;
        })
        .join(","),
    );
    return Buffer.from([header, ...dataRows].join("\n"), "utf-8");
  },
};
